# Generated by Django 6.0.6 on 2026-06-10 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused'), ('not_marked', 'Not marked')], default='not_marked', max_length=20)),
                ('marked_at', models.DateTimeField(auto_now=True)),
                ('marked_by_teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marked_attendance_records', to='accounts.teacherprofile')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='academics.student')),
                ('timetable_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='academics.timetablesession')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'timetable_session', 'date'), name='unique_student_session_attendance_date')],
            },
        ),
    ]
