# Generated by Django 6.0.6 on 2026-06-10 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentstudentrelation',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_relations', to='accounts.parentprofile'),
        ),
        migrations.AddField(
            model_name='student',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.classroom'),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='schools.school'),
        ),
        migrations.AddField(
            model_name='parentstudentrelation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_relations', to='academics.student'),
        ),
        migrations.AddField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='schools.school'),
        ),
        migrations.AddField(
            model_name='teacherclassassignment',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.classroom'),
        ),
        migrations.AddField(
            model_name='teacherclassassignment',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_class_assignments', to='schools.school'),
        ),
        migrations.AddField(
            model_name='teacherclassassignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='teacherclassassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='accounts.teacherprofile'),
        ),
        migrations.AddField(
            model_name='timetablesession',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_sessions', to='academics.classroom'),
        ),
        migrations.AddField(
            model_name='timetablesession',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_sessions', to='schools.school'),
        ),
        migrations.AddField(
            model_name='timetablesession',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_sessions', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='timetablesession',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_sessions', to='accounts.teacherprofile'),
        ),
        migrations.AddConstraint(
            model_name='parentstudentrelation',
            constraint=models.UniqueConstraint(fields=('parent', 'student'), name='unique_parent_student_relation'),
        ),
        migrations.AddConstraint(
            model_name='teacherclassassignment',
            constraint=models.UniqueConstraint(fields=('teacher', 'classroom', 'subject'), name='unique_teacher_class_subject_assignment'),
        ),
    ]
